export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const SELECT_ARTICLES = 'SELECT_ARTICLES'

export const FILTER_ARTICLES_BY_ID = 'FILTER_ARTICLES_BY_ID'

export const SELECT_DATE_RANGE = 'SELECT_DATE_RANGE'

export const FILTER_ARTICLES_BY_DATERANGE = 'FILTER_ARTICLES_BY_DATERANGE'
